New diag: unexpected '...'
quick-lint/quick-lint-js pull request #1032
Opened 2023-06-23 02:52 UTC by isaacnonato

#1023

2023-06-23 02:54 UTC, isaacnonato commented
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

2023-06-23 02:54 UTC, isaacnonato commented
recheck

2023-06-24 01:00 UTC, strager requested changes
Must fix: Please add test cases in test-parse-var.cpp and test-parse-expression.cpp.

In test-parse-var.cpp, test at least these cases:
```javascript
const [a, b, ...] = z;
const {a, b, ...} = z;
```

In test-parse-expression.cpp, test at least these cases:
```javascript
a = ...;
```

I think these two uses of `...` will need different diagnostic messages.

Let me know if you need help writing the tests.

2023-06-27 03:15 UTC, strager approved these changes
Looks good to me. Let me know when I should merge your patch.

2023-06-27 03:15 UTC, strager commented on src/quick-lint-js/fe/parse-expression.cpp
> +    // expression* child = this->parse_expression(v, precedence{.commas = false});
Nit: Delete unused code.
```suggestion

```

2023-06-27 03:15 UTC, strager commented on src/quick-lint-js/fe/parse-expression.cpp
> +  }
Please do not implicitly fall through. Either write `[[fallthrough]];` or (better in this case) repeat the code:
```suggestion
    this->visit_expression(ast->child_0(), v, context);
  }
```

2023-06-27 03:43 UTC, isaacnonato commented
Alright, I have made the suggested changes, I think it can be merged now.
Note: I used `[[fallthrough]];` because the other alternative failed some tests.

2023-06-28 05:21 UTC, strager commented
Landed as commit ec5f3fca3412928b17e54de146872016c28f89aa. (I messed up ownership information for that commit; oops!)

2023-06-28 05:21 UTC, closed without merging

2023-06-28 21:39 UTC, isaacnonato commented
I think this also closes #932.