feat(fe): add warning for 'let({x} = y);'
quick-lint/quick-lint-js pull request #1211
Opened 2024-03-11 21:46 UTC by msharipov

Added a new diagnostic E0720 that closes #1203. Issues a warning when a function let() is called on an object assignment expression.

https://github.com/quick-lint/quick-lint-js/issues/1203

2024-03-13 04:45 UTC, strager requested changes
Looks good overall, but there's a bug which must be fixed ('must fix' comment), and the docs need some improvement ('must fix' comment).

2024-03-13 04:45 UTC, strager commented on src/quick-lint-js/diag/diagnostic-types-2.h
> +                     "let is a function in this scope",
"ambiguous" is incorrect. All JS engines will consider `let` to be a function reference in this case; there is no ambiguity. Perhaps a better word is "confusing": "confusing use of the keyword 'let'; let is a function in this scope"

There's another problem with this message: It doesn't help the user solve the issue. So I propose wording such as the following:
> 'let' is treated as a function; remove parentheses to instead declare a variable

2024-03-13 04:45 UTC, strager commented on src/quick-lint-js/fe/parse-statement.cpp
> +        if (call->child_count() == 2 &&
Must fix: You are missing a check for `call->child_0()`. This code reports a diagnostic for `let.prop({x}=y);` but that code should not have a diagnostic.

2024-03-13 04:45 UTC, strager commented on docs/errors/E0720.md
> +# E0720: calling `let` on an assignment is ambiguous
The title here should match the message in the code:
```suggestion
# E0720: ambiguous use of the keyword 'let'; let is a function in this scope
```

2024-03-13 04:45 UTC, strager commented on docs/errors/E0720.md
> +instead of destructuring `y`.
Must fix: This explanation is wrong. You removed the assignment to `x`. The second snippet should look more like this:
```javascript
function let(arg) {
  console.log(arg);
}

const y = {x: "hello", z: "world"};
({x} = y);      // <-- your explanation is missing this line.
let(y);
```
The explanation also says "If `let` is declared as a function", but it doesn't matter what `let` is declared as (or if it's even declared at all).

Also, the style of the explanation doesn't match our typical style. We shouldn't split the sentence into pieces with code blocks in the middle, and we shouldn't use two code blocks to explain the buggy code.

I suggest a rewrite of this section to something like the following:
```suggestion
In JavaScript, variables can be named `let`. If a `let` statement has parentheses in the wrong spot, `let` itself is treated as a variable name. The statement is thus a function call, not a normal `let` statement:

```javascript
const person = {name: "Alice", age: 9001};
// The following line does
// *not* declare any variables.
let ({name, age} = person);
```-
```

2024-03-13 04:45 UTC, strager commented on docs/errors/E0720.md
> +statements:
The preferred solution is actually to remove parentheses: `let {x} = y;`

2024-03-13 21:27 UTC, msharipov commented
@strager Thank you for the feedback! I have made the necessary corrections to the pull request.

2024-03-16 01:48 UTC, strager commented
Landed your patch as Git commit c8b32584f1ad8d1bc88a293e451886880c6d0bb9.

2024-03-16 01:48 UTC, closed without merging