Report warnings for misuse of --lsp-server
quick-lint/quick-lint-js pull request #208
Opened 2021-04-06 05:47 UTC by LiraNuna

We should warn when the option `--lsp-server` and one of the output formats are chosen since the option is incompatible and therefore ignored.
To detect if an option was given, a new enum value `default_format` was added. The default format is then set to the actual default value in `quick_lint_js::handle_options`.

There are no tests for this, mainly since I couldn't find a test that targets the `o.files_to_lint` check right below, nor a test for `handle_options` at all.

Feedback about this approach is welcomed.

Fixes #202

2021-04-06 05:49 UTC, LiraNuna commented
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

2021-04-06 23:57 UTC, strager approved these changes
Let me know when I should merge this PR.

2021-04-06 23:57 UTC, strager commented on src/main.cpp
> +    }
Minor: Put this logic in `options::dump_errors` (called on line 141 above).

2021-04-07 01:00 UTC, LiraNuna commented
Ready to merge (I would recommend re-review).

2021-04-07 23:23 UTC, strager requested changes

2021-04-07 23:23 UTC, strager commented on test/test-options.cpp
> +    EXPECT_TRUE(have_errors);
Shouldn't `have_errors` be false, since we only saw warnings?

2021-04-07 23:23 UTC, strager commented on test/test-options.cpp
> +  }
Minor: Instead of repeating the code, loop over different `output_format`s?

2021-04-07 23:23 UTC, strager commented on test/test-options.cpp
> +              "warning: output format ignored with --lsp-server\n");
Nit: Reword to: "warning: --output-format ignored with --lsp-server"

2021-04-08 00:19 UTC, strager approved these changes
:heart:
Let me know when I should merge this.

2021-04-08 00:19 UTC, strager commented on test/test-options.cpp
> +    for (const auto &format : output_formats) {
Nit: You can inline `output_formats`:

```cpp
    for (const auto &format : {
        /* default_format intentionally left out */
        output_format::gnu_like,
        output_format::vim_qflist_json,
    }) {
```

2021-04-08 00:52 UTC, LiraNuna commented on test/test-options.cpp
> +    for (const auto &format : output_formats) {
did not know that! modern C++ is neat.

2021-04-08 06:29 UTC, LiraNuna commented
Ready

2021-04-08 08:37 UTC, strager commented
Landed as commit 20c2886abf96950aedc121decbf5804bd8fe9c56.

2021-04-08 08:37 UTC, closed without merging