Doc: make contributors and error codes valid markdown.
quick-lint/quick-lint-js pull request #668
Opened 2022-03-15 17:43 UTC by LeeWannacott

I copied over the error codes from the website (including descriptions) which might  be overkill?, maybe you only wanted the ones already in the changelog.md :thinking: 

Also I used `<br>` to break lines instead of two white-spaces on the end because harder to see that...

GitHub Flavored Markdown Specification: https://github.github.com/gfm/

Looks like the syntax you had was for reference links:
```
[foo][bar]

[bar]: /url "title"
```

2022-03-15 19:35 UTC, strager requested changes
Must fix: I don't understand the point of your change. It [break the links](https://github.com/quick-lint/quick-lint-js/blob/e6c5cb71510b24a60719882d2f85cb096b124feb/docs/CHANGELOG.md) in the content above. See screenshot:

<img width="1237" alt="Screen Shot 2022-03-15 at 12 32 56 PM" src="https://user-images.githubusercontent.com/48666/158456976-d5b3a9d4-0773-442e-abd8-9812b808bead.png">

compared to [before your change](https://github.com/quick-lint/quick-lint-js/blob/61372e366c86e5f4c1b2cf405c060afc20da57fd/docs/CHANGELOG.md):

<img width="1298" alt="Screen Shot 2022-03-15 at 12 33 28 PM" src="https://user-images.githubusercontent.com/48666/158457069-0f4660c2-a505-40f6-8f61-517f69057d22.png">

> Looks like the syntax you had was for reference links:

Exactly. Why did you break this?

2022-03-15 19:35 UTC, strager commented on docs/CHANGELOG.md
> +- [AidenThing](https://github.com/AidenThing)<br>
Must fix: A visible list doesn't belong in CHANGELOG.md. We already have AUTHORS.md for the contributor list. Undo this change.

2022-03-15 19:35 UTC, strager commented on docs/CHANGELOG.md
> +- [E0001](https://quick-lint-js.com/errors/E0001/): variable assigned before its declaration<br>
Must fix: A list of error codes doesn't belong in CHANGELOG.md. I don't know what the purpose of this change is for. Undo.

2022-03-16 00:27 UTC, LeeWannacott commented
Closing PR as the changelog reference links work as intended...

2022-03-16 00:27 UTC, closed without merging