Warn on 'await await'
quick-lint/quick-lint-js pull request #785
Opened 2022-07-12 18:06 UTC by clegoz

Resolves #776

2022-07-12 18:13 UTC, clegoz commented
I have read and hereby agree to quick-lint-js' Contributor License Agreement (CLA-v1.md).

2022-07-13 21:44 UTC, strager requested changes

2022-07-13 21:44 UTC, strager commented on src/quick-lint-js/diagnostic-types.h
> +      diag_redundant_await, "E0260", diagnostic_severity::warning,             \
Nit: Sort alphabetically by struct name (`diag_redundant_await`).

2022-07-13 21:44 UTC, strager commented on test/test-parse-expression.cpp
> +  {
Nit: I'd put this in a separate `TEST` so it's better documented.

2022-07-13 21:44 UTC, strager commented on test/test-parse-expression.cpp
> +                                  diag_await_operator_outside_async))));
Must fix: Negative assertions are bad and we should avoid them if possible.

If the diagnostics change for only one test case, we should special-case that test case (similar to what we do on line 1126).

2022-07-13 21:44 UTC, strager commented on test/test-parse-expression.cpp
> +                                  diag_await_operator_outside_async))));
Must fix: Same comment as on line 1153-4.

2022-07-13 21:44 UTC, strager commented on test/test-parse.cpp
> +                              DIAG_TYPE(diag_depth_limit_exceeded))));
Note: Generally, negative assertions are bad. In this case, I think it's fine. You can leave this code as-is.

2022-07-13 21:46 UTC, strager commented
I fixed the "Homebrew package / macOS 10.15" CI failure on master. Please rebase/merge.

2022-07-14 01:54 UTC, strager approved these changes

2022-07-14 09:05 UTC, closed without merging