Check go version and xgettext
quick-lint/quick-lint-js pull request #882
Opened 2022-11-05 03:37 UTC by AlekLefebvre

Implements #833

2022-11-15 19:52 UTC, strager requested changes
This check is broken if `go` is not installed. Here's the output I get:
```
$ ./tools/update-translator-sources
./tools/update-translator-sources: line 19: go: command not found
warning: Go version 1.16 or above required. You are using version
updating: po/messages.pot
........................................ done.
updating: po/de.po
........................................ done.
updating: po/en_US@snarky.po
........................................ done.
updating: po/fr_FR.po
........................................ done.
updating: po/pt_BR.po
........................................ done.
updating: po/sv_SE.po
........................................ done.
./tools/update-translator-sources: line 15: go: command not found
```

---

Must fix: This check is broken if `xgettext` is not installed. Here's the output I get:
```
$ ./tools/update-translator-sources
$ echo $?
127
```

2022-11-15 19:52 UTC, strager commented on tools/update-translator-sources
> +  if [ "$(printf '%s\n' "$min_go_version" "$go_version" | sort -V | head -n1)" = "$go_version" ]; then
This is a clever way to compare versions!

2022-11-15 19:52 UTC, strager commented on tools/update-translator-sources
> +#!/bin/bash
Nit: This should be `#!/usr/bin/env bash`.

2022-11-16 03:38 UTC, AlekLefebvre commented
I fixed the issues and also fixed the error 127 when clang-format is not installed in tools/format.

2022-11-17 04:12 UTC, strager approved these changes

2022-11-17 04:13 UTC, merged